name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade python environment
      run: python -m pip install --upgrade virtualenv setuptools pip
    - name: Upgrade test dependencies
      run: python -m pip install psutil pytest 'hypothesis[zoneinfo]' qiskit
    - name: Install JAX
      run: pip install jax
    - name: Install QFactor JAX
      run: pip install .
    - name: Run tests
      env:
        AMOUNT_OF_WORKERS: 2
      run: pytest
